name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão para push no repositório

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Gerando a Snake Animation sem `set-output`
      - name: Generate Snake Animation
        run: |
          curl -o snake.svg "https://github.com/Platane/snk/raw/output/github-contribution-grid-snake.svg"
          mkdir -p dist
          mv snake.svg dist/github-contribution-grid-snake.svg

      # Deploy para a branch output (versão mais recente da ação)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.2.0  # Última versão estável
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
