name: Generate Datas

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiss찾o para push no reposit처rio

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Garante acesso ao reposit처rio

      # Atualizando o Platane/snk para a vers찾o 3.1.0
      - name: Generate Snake Animation
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: AmaranteCarol-dev
          outputs: dist/github-contribution-grid-snake.svg

      # Deploy para a branch output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
